--------------------------------------------------------------------------------
-- SEIS 630 Final Project Schema
--------------------------------------------------------------------------------
-- TABLES
--------------------------------------------------------------------------------
-- Create Table Order: stock_sector > stocks > stock_history > watchlist 
--                     > watchlist_history
--------------------------------------------------------------------------------
-- Drop Table Order: watchlist_history > watchlist > stock_history > stocks
--                  > stock_sector
--------------------------------------------------------------------------------

--Stock sector table
CREATE TABLE stock_sector (
    sector_id     NUMBER GENERATED BY DEFAULT AS IDENTITY,
    sector_name   VARCHAR2(50) NOT NULL UNIQUE,
    CONSTRAINT pk_sector_ref PRIMARY KEY (sector_id)
);

-- Stocks Table
CREATE TABLE stocks (
    ticker          VARCHAR2(10) NOT NULL,
    exchange        VARCHAR2(15) NOT NULL,
    company_name    VARCHAR2(100),
    close_price     NUMBER(12,4),
    daily_return    NUMBER(12,6),
    rsi             NUMBER(12,6),
    return_1m       NUMBER(12,6),
    return_3m       NUMBER(12,6),
    return_12m      NUMBER(12,6),
    ma_50           NUMBER(12,4),
    ma_50_30d_ago   NUMBER(12,4),
    ma_200          NUMBER(12,4),
    vol_3m          NUMBER(20,6),
    downside_vol_3m NUMBER(20,6),
    idiosync_vol_1y NUMBER(12,6),
    sharpe_1y       NUMBER(12,6),
    beta_1y         NUMBER(12,6),
    market_cap      NUMBER(20,0),
    sector_id       NUMBER NOT NULL,
    signal          CHAR(1) CHECK (signal IN ('Y','N')),
    eval_date       DATE NOT NULL,
    source          VARCHAR2(50),
    vol_z           NUMBER(12,6),
    sharpe_1y_z     NUMBER(12,6),
    downside_vol_z  NUMBER(12,6),
    idiosync_vol_z  NUMBER(12,6),
    safety_score    NUMBER(6,2),
    safety_CI_low   NUMBER(6,2),
    safety_CI_high  NUMBER(6,2),
    CONSTRAINT pk_stocks PRIMARY KEY (ticker, exchange),
    CONSTRAINT fk_stocks_sector FOREIGN KEY (sector_id)
    REFERENCES stock_sector(sector_id)
);

-- Stock History Table
CREATE TABLE stock_history (
    ticker          VARCHAR2(10) NOT NULL,
    exchange        VARCHAR2(15) NOT NULL,
    company_name    VARCHAR2(100),
    close_price     NUMBER(12,4),
    daily_return    NUMBER(12,6),
    rsi             NUMBER(12,6),
    return_1m       NUMBER(12,6),
    return_3m       NUMBER(12,6),
    return_12m      NUMBER(12,6),
    ma_50           NUMBER(12,4),
    ma_50_30d_ago   NUMBER(12,4),
    ma_200          NUMBER(12,4),
    vol_3m          NUMBER(20,6),
    downside_vol_3m NUMBER(20,6),
    idiosync_vol_1y NUMBER(12,6),
    sharpe_1y       NUMBER(12,6),
    beta_1y         NUMBER(12,6),
    market_cap      NUMBER(20,0),
    sector_id       NUMBER NOT NULL,
    signal          CHAR(1) CHECK (signal IN ('Y','N')),
    eval_date       DATE NOT NULL,
    source          VARCHAR2(50),
    vol_z           NUMBER(12,6),
    sharpe_1y_z     NUMBER(12,6),
    downside_vol_z  NUMBER(12,6),
    idiosync_vol_z  NUMBER(12,6),
    safety_score    NUMBER(6,2),
    safety_CI_low   NUMBER(6,2),
    safety_CI_high  NUMBER(6,2),
    CONSTRAINT pk_stock_history PRIMARY KEY (ticker, exchange, eval_date),
    CONSTRAINT fk_stocks_hist_sector FOREIGN KEY (sector_id)
    REFERENCES stock_sector(sector_id),
    CONSTRAINT fk_wh_stocks FOREIGN KEY (ticker, exchange)
    REFERENCES stocks (ticker, exchange)
);

-- Watchlist table
CREATE TABLE watchlist (
    ticker        VARCHAR2(10) NOT NULL,
    exchange      VARCHAR2(15) NOT NULL,
    safety_score  NUMBER(6,2),
    eval_date     DATE NOT NULL,
    added_at      DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_watchlist PRIMARY KEY (ticker, exchange),
    CONSTRAINT fk_watchlist_stocks FOREIGN KEY (ticker, exchange)
        REFERENCES stocks(ticker, exchange)
);

-- Watchlist History table
CREATE TABLE watchlist_history (
    ticker        VARCHAR2(10) NOT NULL,
    exchange      VARCHAR2(15) NOT NULL,
    safety_score  NUMBER(6,2),
    snapshot_date DATE NOT NULL,
    action        VARCHAR2(10) CHECK (action IN ('ENTERED','DROPPED','SNAPSHOT')),
    PRIMARY KEY (ticker, exchange, snapshot_date, action)
);

--------------------------------------------------------------------------------
-- Table Altering: Confidence Intervals did not work out
ALTER TABLE stocks
    DROP COLUMN safety_CI_low;

ALTER TABLE stocks
    DROP COLUMN safety_CI_high;

ALTER TABLE stock_history
    DROP COLUMN safety_CI_low;

ALTER TABLE stock_history
    DROP COLUMN safety_CI_high;
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
--Table Protection (if necessary)
--LOCK TABLE watchlist IN EXCLUSIVE MODE;
--LOCK TABLE watchlist_history IN EXCLUSIVE MODE;
--------------------------------------------------------------------------------
-- Watchlist Procedure
CREATE OR REPLACE PROCEDURE refresh_watchlist AS
BEGIN
    ------------------------------------------------------------------
    -- Log ENTERED (new stocks not in current watchlist)
    ------------------------------------------------------------------
    INSERT INTO watchlist_history (ticker, exchange, safety_score, snapshot_date, action)
    WITH new_top25 AS (
        SELECT ticker,
               exchange,
               safety_score,
               eval_date
        FROM (
            SELECT ticker,
                   exchange,
                   safety_score,
                   eval_date,
                   ROW_NUMBER() OVER (ORDER BY safety_score DESC) AS rn
            FROM stocks
            WHERE safety_score IS NOT NULL
            and sharpe_1y > -0.1
            and signal = 'Y'
        )
        WHERE rn <= 25
    )
    SELECT n.ticker, n.exchange, n.safety_score, n.eval_date, 'ENTERED'
    FROM new_top25 n
    LEFT JOIN watchlist w
      ON w.ticker = n.ticker AND w.exchange = n.exchange
    WHERE w.ticker IS NULL;
    ------------------------------------------------------------------
    -- Log DROPPED (stocks removed from watchlist)
    ------------------------------------------------------------------
    INSERT INTO watchlist_history (ticker, exchange, safety_score, snapshot_date, action)
    WITH new_top25 AS (
        SELECT ticker,
               exchange,
               safety_score,
               eval_date
        FROM (
            SELECT ticker,
                   exchange,
                   safety_score,
                   eval_date,
                   ROW_NUMBER() OVER (ORDER BY safety_score DESC) AS rn
            FROM stocks
            WHERE safety_score IS NOT NULL
            and sharpe_1y > -0.1
            and signal = 'Y'
        )
        WHERE rn <= 25
    )
    SELECT w.ticker, w.exchange, w.safety_score, w.eval_date, 'DROPPED'
    FROM watchlist w
    LEFT JOIN new_top25 n
      ON w.ticker = n.ticker AND w.exchange = n.exchange
    WHERE n.ticker IS NULL;
    ------------------------------------------------------------------
    -- Log SNAPSHOT
    ------------------------------------------------------------------
    INSERT INTO watchlist_history (ticker, exchange, safety_score, snapshot_date, action)
    WITH new_top25 AS (
        SELECT ticker,
               exchange,
               safety_score,
               eval_date
        FROM (
            SELECT ticker,
                   exchange,
                   safety_score,
                   eval_date,
                   ROW_NUMBER() OVER (ORDER BY safety_score DESC) AS rn
            FROM stocks
            WHERE safety_score IS NOT NULL
            and sharpe_1y > -0.1
            and signal = 'Y'
        )
        WHERE rn <= 25
    )
    SELECT ticker, exchange, safety_score, eval_date, 'SNAPSHOT'
    FROM new_top25;
    ------------------------------------------------------------------
    -- Replace watchlist
    ------------------------------------------------------------------
    DELETE FROM watchlist;

    INSERT INTO watchlist (
        ticker,
        exchange,
        safety_score,
        eval_date,
        added_at)
    WITH new_top25 AS (
        SELECT ticker,
            exchange,
            safety_score,
            eval_date
        FROM (
        SELECT ticker,
            exchange,
            safety_score,
            eval_date,
            ROW_NUMBER() OVER (ORDER BY safety_score DESC) AS rn
        FROM stocks
        WHERE safety_score IS NOT NULL
        and sharpe_1y > -0.1
        and signal = 'Y'
        )
    WHERE rn <= 25)
SELECT 
       ticker,
       exchange,
       safety_score,
       eval_date,
       eval_date 
FROM new_top25;
END;
/
--------------------------------------------------------------------------------
--Manual Watchlist Refresh
BEGIN
    refresh_watchlist;
END;
/
--------------------------------------------------------------------------------
-- Indexes
CREATE INDEX idx_stock_eval_date ON stock_history(eval_date);
--Composite index for per-ticker queries ("when did ABCD drop out of watchlist?")
CREATE INDEX idx_wh_ticker_exch_date
ON watchlist_history (ticker, exchange, snapshot_date);
--Date-centric index for reporting & snapshots (daily summaries)
CREATE INDEX idx_wh_snapshot_date ON watchlist_history (snapshot_date);
--Index on action for analytics (lots of snapshots to go through)
CREATE INDEX idx_wh_action ON watchlist_history (action);
-- Index on Stocks to increase refresh_watchlist speed
CREATE INDEX idx_stocks_signal_safety
ON stocks (signal, sharpe_1y, safety_score);
--------------------------------------------------------------------------------
-- Triggers 
CREATE OR REPLACE TRIGGER trg_stocks_to_history
BEFORE UPDATE ON stocks
FOR EACH ROW
BEGIN
    IF :OLD.close_price   <> :NEW.close_price   OR
       :OLD.daily_return  <> :NEW.daily_return  OR
       :OLD.rsi           <> :NEW.rsi           OR
       :OLD.return_1m     <> :NEW.return_1m     OR
       :OLD.return_3m     <> :NEW.return_3m     OR
       :OLD.return_12m    <> :NEW.return_12m    OR
       :OLD.ma_50         <> :NEW.ma_50         OR
       :OLD.ma_50_30d_ago <> :NEW.ma_50_30d_ago OR
       :OLD.ma_200        <> :NEW.ma_200        OR
       :OLD.vol_3m        <> :NEW.vol_3m        OR
       :OLD.sharpe_1y     <> :NEW.sharpe_1y     OR
       :OLD.beta_1y       <> :NEW.beta_1y       OR
       :OLD.market_cap    <> :NEW.market_cap    OR
       :OLD.safety_score  <> :NEW.safety_score  OR
       :OLD.eval_date     <> :NEW.eval_date     OR
       :OLD.vol_z         <> :NEW.vol_z         OR
       :OLD.sharpe_1y_z   <> :NEW.sharpe_1y_z   OR
       :OLD.downside_vol_z <> :NEW.downside_vol_z OR
       :OLD.idiosync_vol_z <> :NEW.idiosync_vol_z
    THEN
        INSERT INTO stock_history (
            ticker,
            exchange,
            company_name,
            close_price,
            daily_return,
            rsi,
            return_1m,
            return_3m,
            return_12m,
            ma_50,
            ma_50_30d_ago,
            ma_200,
            vol_3m,
            downside_vol_3m,
            idiosync_vol_1y,
            sharpe_1y,
            beta_1y,
            market_cap,
            sector_id,
            signal,
            eval_date,
            source,
            vol_z,
            sharpe_1y_z,
            downside_vol_z,
            idiosync_vol_z,
            safety_score
        )
        VALUES (
            :OLD.ticker,
            :OLD.exchange,
            :OLD.company_name,
            :OLD.close_price,
            :OLD.daily_return,
            :OLD.rsi,
            :OLD.return_1m,
            :OLD.return_3m,
            :OLD.return_12m,
            :OLD.ma_50,
            :OLD.ma_50_30d_ago,
            :OLD.ma_200,
            :OLD.vol_3m,
            :OLD.downside_vol_3m,
            :OLD.idiosync_vol_1y,
            :OLD.sharpe_1y,
            :OLD.beta_1y,
            :OLD.market_cap,
            :OLD.sector_id,
            :OLD.signal,
            :OLD.eval_date,
            :OLD.source,
            :OLD.vol_z,
            :OLD.sharpe_1y_z,
            :OLD.downside_vol_z,
            :OLD.idiosync_vol_z,
            :OLD.safety_score
        );
    END IF;
END;
/
--------------------------------------------------------------------------------
-- Daily Scheduler
--BEGIN
--    DBMS_SCHEDULER.CREATE_JOB (
--        job_name        => 'JOB_WATCHLIST',
--        job_type        => 'STORED_PROCEDURE',
--        job_action      => 'REFRESH_WATCHLIST',
--        start_date      => SYSTIMESTAMP,
--        repeat_interval => 'FREQ=DAILY; BYHOUR=17; BYMINUTE=0; BYSECOND=0',
--        enabled         => TRUE
--    );
--END;
--/
--
--BEGIN
--    DBMS_SCHEDULER.RUN_JOB('JOB_REFRESH_WATCHLIST');
--END;
--/

--Checking Job Status
--SELECT job_name, state, last_start_date, next_run_date
--FROM user_scheduler_jobs
--WHERE job_name = 'JOB_REFRESH_WATCHLIST';
--
--SELECT *
--FROM user_scheduler_job_run_details
--WHERE job_name = 'JOB_REFRESH_WATCHLIST'
--ORDER BY log_id DESC;
--
----Disable Job
--BEGIN
--    DBMS_SCHEDULER.DISABLE('JOB_WATCHLIST');
--END;
--/

--Enable Job
--BEGIN
--    DBMS_SCHEDULER.ENABLE('JOB_REFRESH_WATCHLIST');
--END;
--/
--------------------------------------------------------------------------------

--Views

CREATE OR REPLACE VIEW vw_watchlist_movement AS
SELECT h.ticker,
       h.safety_score,
       h.snapshot_date,
       h.action
FROM watchlist_history h
ORDER BY h.snapshot_date DESC;

CREATE OR REPLACE VIEW vw_avg_safety_by_sector AS
SELECT 
       sctr.sector_name,
       ROUND(AVG(stk.safety_score), 2) AS avg_safety_score,
       COUNT(*) AS sector_count
FROM stock_history stk
JOIN stock_sector sctr
    ON stk.sector_id = sctr.sector_id
WHERE stk.safety_score IS NOT NULL
GROUP BY sctr.sector_name
ORDER BY avg_safety_score DESC;

CREATE OR REPLACE VIEW vw_avg_safety_by_stock AS
SELECT
        stk.ticker,
        ROUND(AVG(stk.safety_score), 2) as avg_safety_score
FROM stock_history stk
WHERE stk.safety_score IS NOT NULL
GROUP BY stk.ticker
ORDER BY avg_safety_score DESC
;

